server:
  port: 8081

spring:
  application:
    name: scm2.0

  #db configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scm2
    username: root
    password: Welcome@1

  #jpa configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   #for creating schemas and tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




